ent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from .views import index, about, section, tests,  test_detail, leave_comment, article_detail, leave_test, result, registration, registration_result, qwe, logout_user, authenticate_result
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', section, name='home'),
    path('about', about, name='about'),
    path('section', section, name='section'),
    path('tests', tests, name='tests'),
    path('section/<slug:slug>', article_detail, name='detail'),
    path('section/<slug:slug>/leave_comment', leave_comment, name='leave_comment'),
    path('tests/<slug:slug>', test_detail, name='test_detail'),
    path('tests/<slug:slug>/leave_test', leave_test, name='leave_test'),
    path('tests/<slug:slug>/result', result, name='result'),
    path('registration', registration, name='registration'),
    path('registration_result', registration_result, name='registration_result'),
    path('authenticate', qwe, name='authenticate'),
    path('authenticate/result', authenticate_result, name='authenticate_result'),
    path('logout_user', logout_user, name='logout_user'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.db.models import ImageField
from django.urls import reverse

class Article(models.Model):
    article_title = models.CharField('Название урока', max_length=200)
    article_img1 = models.ImageField(upload_to="image/", null=True, blank=True)
    article_img2 = models.ImageField(upload_to="image/", null=True, blank=True)
    article_text1 = models.TextField('Текст статьи')
    article_text2 = models.TextField('Текст статьи', null=True)
    article_text3 = models.TextField('Текст статьи', null=True)
    article_text4 = models.TextField('Текст статьи', null=True)
    article_text5 = models.TextField('Текст статьи', null=True)
    article_text6 = models.TextField('Текст статьи', null=True)
    article_text7 = models.TextField('Текст статьи', null=True)
    article_text8 = models.TextField('Текст статьи', null=True)
    article_text9 = models.TextField('Текст статьи', null=True)
    article_text10 = models.TextField('Текст статьи', null=True)
    slug = models.SlugField(null=False, unique=True)

    def __str__(self):
        return self.article_title

    def get_absolute_url(self):
        return reverse("main:detail", kwargs={"slug": self.slug})

    def get_test_url(self):
        return reverse("main:test_detail", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'



class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('Никнейм', max_length=200)
    text = models.TextField('Текст комментария')


class Test(models.Model):
    question = models.CharField('Вопрос', max_length=200)
    img = models.ImageField(upload_to="image/", null=True, blank=True)
    answer1 = models.CharField('Вариант1', max_length=200)
    answer2 = models.CharField('Вариант2', max_length=200)
    answer3 = models.CharField('Вариант3', max_length=200)
    answer4 = models.CharField('Вариант4', max_length=200)
    answer5 = models.CharField('Вариант5', max_length=200, null=True)
    correct = models.CharField('Правильный вариант ответа', max_length=200)
    slug = models.SlugField(null=False, unique=False)

    def get_test_url(self):
        return reverse("main:test_detail", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'


class Choice(models.Model):
    ip = models.CharField('IP', max_length=200, null=True)
    question = models.CharField('Вопрос', max_length=200, null=True)
    answer = models.CharField('Вариант', max_length=200, null= True)
    correct = models.CharField('Правильный', max_length=200, null= True)
    slug = models.SlugField(null=True, unique=False)

main/forms.py
from .models import Choice
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm

class AuthUser(forms.ModelForm):
	class Meta:
		model = Choice
		fields = ('username', 'password')

main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Test, Choice
from django.views.generic import DetailView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import authenticate, login, logout

def index(request):
    return render(request, 'main/index.html')

def about(request):
    return render(request, 'main/about.html')

def section(request):
    article = Article.objects.order_by('-id')
    return render(request, 'main/section.html', {'title':'Теория', 'article': article})

def tests(request):
    article = Article.objects.order_by('-id')
    return render(request, 'main/tests.html', {'title':'Теория', 'article': article})



def leave_comment(request, slug):
    a = Article.objects.get(slug=slug)
    a.comment_set.create(author_name=request.user, text=request.POST['text'])

    return HttpResponseRedirect(reverse('main:detail', args=(slug,)))



def test_detail(request, slug):
    tests = Test.objects.filter( slug=slug)
    context = {'tests':tests, 'slug':slug}
    return render(request, 'main/test_detail.html', context)

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def article_detail(request, slug):
    model = Article.objects.get( slug = slug)
    comments = model.comment_set.order_by('-id')
    context = {'object': model, 'comments':comments, 'slug':slug}
    return render(request, 'main/article_detail.html', context)


def leave_test(request, slug):
    global c
    global m
    c = 0
    '''user = request.user
                choices = Choice.objects.filter( slug=slug) 
                for choice in choices:
                    if str(choice.ip) == str(user):
                        choice.delete()
                    '''
    user = get_client_ip(request)
    choices = Choice.objects.filter( slug=slug) 
    for choice in choices:
        if str(choice.ip) == str(user):
            choice.delete()
    tests = Test.objects.filter( slug=slug) 
    m = len(tests)
    ip = user
    for test in tests:

        answer = request.POST[test.question]
        
        if answer == test.correct:
            a = Choice(ip=ip, question=test.question, answer=answer, correct=test.correct, slug=slug)
            a.save()
            c = c + 1
        else:
            a = Choice(ip=ip, question=test.question, answer=answer, correct=test.correct, slug=slug)
            a.save()
    return HttpResponseRedirect(reverse('main:result', args=(slug,)))

def result(request, slug):
    d = c
    f = m
    ip = get_client_ip(request)
    user = request.user
    user = str(user)
    tests = Test.objects.filter( slug=slug)
    choices = Choice.objects.filter(slug=slug)
    context = {'tests':tests,'slug':slug, 'ip':ip, 'choices':choices, 'c':d, 'm':f, 'user':user}
    return render(request, 'main/result.html', context)

def registration(request):
    return render(request, 'main/registration.html')

def registration_result(request):
    username = request.POST['username']
    password1 = request.POST['password1']
    password2 = request.POST['password2']
    userpost = request.POST['userpost']
    try:
        user = User.objects.get(username=username)
        error = 'Имя пользователя занято'
        return render(request, 'main/registration.html', {'error':error})
    except User.DoesNotExist:
        if password1 != password2:
            error = 'Пароли должны быть одинаковыми'
            return render(request, 'main/registration.html', {'error':error})
        else:
            user = User.objects.create_user(username, userpost, password1)
            user.save()
            user = authenticate(request, username=username, password=password1)
            login(request, user)
            return HttpResponseRedirect(reverse('main:home', args=()))

def qwe(request):
    return render(request, 'main/authenticate.html')

def authenticate_result(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('main:home'))
    else:
        error = 'Неверный пароль или имя пользователя'
        return render(request, 'main/authenticate.html', {'error':error})

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('main:home'))
    

main/templates/main/about.html
{% extends 'main/base.html' %}
{% block title %}
ASD
{% endblock %}

{% block content %}
	<div class="content-bigbox">
		<h1 class="content-bigbox-text-h">Эта страница в разработке</h1>
		<a href="logout_user">Выйти из аккаунта</a>
	</div>
{% endblock %}

main/templates/main/article_detail.html
{% extends 'main/base.html' %}
{% block title %}
  {{ object.article_title }}
{% endblock %}
{% block content %}

    <div class="article-box">
          <h1 class="article-box-text-h">{{ object.article_title }}</h1>
          <p class="article-box-text">{{ object.article_text1 }}</p>
          {% if object.article_text2 %}
          <p class="article-box-text">{{ object.article_text2 }}</p>
          {% endif %}
          {% if object.article_text3 %}
          <p class="article-box-text">{{ object.article_text3 }}</p>
          {% endif %}
          {% if object.article_text4 %}
          <p class="article-box-text">{{ object.article_text4 }}</p>
          {% endif %}
          {% if object.article_text5 %}
          <p class="article-box-text">{{ object.article_text5 }}</p>
          {% endif %}
          {% if object.article_text6 %}
          <p class="article-box-text">{{ object.article_text6 }}</p>
          {% endif %}
          {% if object.article_text7 %}
          <p class="article-box-text">{{ object.article_text7 }}</p>
          {% endif %}
          {% if object.article_text8 %}
          <p class="article-box-text">{{ object.article_text8 }}</p>
          {% endif %}
          {% if object.article_text9 %}
          <p class="article-box-text">{{ object.article_text9 }}</p>
          {% endif %}
          {% if object.article_text10 %}
          <p class="article-box-text">{{ object.article_text10 }}</p>
          {% endif %}

          <div class="article-box-link-shell-1">
            <a class="article-box-link-3" href="{{ object.get_test_url }}"> <h3>Пройти тест по теме?</h3></a>
          </div>   
    </div>   
    <div class="article-commentbox">
      
      {% if request.user.is_authenticated %}
      
      <div class="article-comment-input">
      <form action="{{object.get_absolute_url }}/leave_comment" method="POST">
          {% csrf_token %}
          <input required placeholder="Текст комментария" name="text"></textarea><br>
          <button class="btn" type="submit">Оставить комментарий</button>
        </form>
     
      {% else %}
        <p>Чтобы оставлять комментарии нужно быть зерегистрированным</p>
      {% endif %}
        {% if comments %}
                {% for comment in comments %}
                <div class="article-comment">
                  <h4 class="article-comment-h">{{ comment.author_name }}</h4>
                  <p class="article-comment-p">{{ comment.text }}</p>
                </div>
                {% endfor %}
                {% else %}
                <p>Нет комментариев</p>
                {% endif %}
       </div>
        
        
{% endblock %}

main/templates/main/authenticate.html
{% extends 'main/base.html' %}
{% block title %}
  Аутентификая
{% endblock %}
{% block content %}
  <form action="authenticate/result" method="POST">
    {% csrf_token %}
    <input class="input" placeholder="Введите имя пользователя" type="text" name="username"><br>
    <input class="input" placeholder="Введите пароль" type="password" name="password"><br>
    <p>{{ error }}</p>
    <button class="btn" type="submit">Войти</button>
  </form>
{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content='width=device-width'>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;500&display=swap" rel="stylesheet">
  {% load static %}
  <link href="{% static 'main/css/asdasd.css'%}" rel="stylesheet">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header  id="header" class='header'>
        <div class="header-inner">
          <a class="header-link" href="{% url 'main:section' %}">
            <div class="header-logo-full">
              <img src="{% static 'main/img/qwe.png' %}">
              <p class="header-logo-text">Ez informatics</p>
            </div>
          </a>
          <a class="burger">
            <span></span>
            <span></span>
            <span></span>
          </a>
          <ul class="nav">
            
            <a id="{% if request.path == '/section' %}current{% endif %}" class='nav-link' href="{% url 'main:section' %}">Разделы</a>
            <a id="{% if request.path == '/tests' %}current{% endif %}" class='nav-link' href="{% url 'main:tests' %}">Тесты</a>
            {% if user.is_authenticated %}
            
              <a id="{% if request.path == '/about' %}current{% endif %}" class='nav-link' href="{% url 'main:about' %}">{{user}}</a>
            
            {% else %} 
              <a class='nav-link' href="{% url 'main:authenticate' %}">Вход</a>
              <b><a class='nav-link' href="{% url 'main:registration' %}">Регистрация</a></b>
             

            {% endif %}
        </ul>
        </div>
    </header>

    <content class='content'>
      <div class="conteiner">
        {% block content %}{% endblock %}
      </div>
    </content>

  <script>
    window.onscroll = function() {myFunction()};

    function myFunction() {
      if (document.documentElement.scrollTop > 12) {
        document.getElementById("header").className = "header-fixed";
      } else {
        document.getElementById("header").className = "header";
      }
    }
    let menuBtn = document.querySelector('.burger');
    let menu = document.querySelector('.nav');
    menuBtn.addEventListener('click', function(){
      menuBtn.classList.toggle('active');
      menu.classList.toggle('active');
    })

  </script>
</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block title %}
Главная страница
{% endblock %}

{% block content %}
	<div class="content-boxes">
		<div class="content-box">
			<a href="{% url 'main:tests' %}" class="content-box-link">
			{% load static %}
			<img class="content-box-img" src="{% static 'main/img/main1.jfif'%}" alt="Картинка">
			<p class="content-box-text-1">Пройди тест и оцени свой уровень знаний</p>
			
				</a>
			
		</div>
		<div class="content-box">
			<a href="{% url 'main:section' %}" class="content-box-link">
			<img class="content-box-img" src="{% static 'main/img/main2.jpg'%}" alt="Картинка">
			<p class="content-box-text">Подучить материал?</p>
			
			</a>
		</div>
		<div class="content-box">
			<a href="{% url 'main:tests' %}" class="content-box-link">
			<img class="content-box-img" src="{% static 'main/img/main3.png'%}" alt="Картинка">
			<p class="content-box-text">Пора приступить к практике?</p>
			
				<a href="{% url 'main:tests' %}" class="content-box-link"></a>
		</div>
	</div>

{% endblock %}

main/templates/main/registration.html
{% extends 'main/base.html' %}
{% block title %}
  Регистация
{% endblock %}
{% block content %}
  <form action="/registration_result" method="POST">
    {% csrf_token %}
    <input class="input" placeholder="Введите имя пользователя" type="text" name="username"><br>
    <input class="input" placeholder="Введите почту" type="text" name="userpost"><br>
    <input class="input" placeholder="Введите пароль" type="password" name="password1"><br>
    <input class="input" placeholder="Введите пароль повторно" type="password" name="password2"><br>
    <button class="btn" type="submit">Зарегестрироваться</button><br>
    <p>{{ error }}</p>
  </form>
{% endblock %}

main/templates/main/result.html
{% extends 'main/base.html' %}
{% block title %}
  {{ slug }}
{% endblock %}
{% block content %}
    <div class="form-box">
      <p class="form-bigbox-text-3">Правильно решено {{ c }}/{{ m }}</p>
      <a class="" href="/tests/{{slug}}">Пересдать?</a>
    </div>
  	{% for choice in choices %}
      {% if user == choice.ip %}
        {% if choice.slug == slug %}
          {% if choice.correct == choice.answer %}

            <div class="form-box-true">
              <h3>{{ choice.question }}</h2>
              <p>Ваш ответ: {{ choice.mark }} {{ choice.answer }}</p>
              <p>Правильный ответ!</p>
            </div>

          {% else %}

            <div class="form-box-false">
              <h2>{{ choice.question }}</h2>
              <p>Ваш ответ: {{ choice.mark }} {{ choice.answer }}</p>
              <p>Правильный ответ: {{choice.correct}}</p>
            </div>
          {% endif %}
        {% endif %}
      {% endif %}
    {% endfor %}
      
{% endblock %}

main/templates/main/section.html
{% extends 'main/base.html' %}
{% block title %}
{{ title }}
{% endblock %}

{% block content %}
  <div class="content-boxes">
    {% for el in article %}
      
        <div class="content-box">
          <a href="{{el.get_absolute_url }}" class='content-box-link'>      
          <img align="left" class="content-box-img" src="{{ el.article_img1.url }}" alt="Картинка">
          <p class="content-h2">{{ el.article_title }}</p>      
      </a>        
      </div>
    {% endfor %}
  </div>
{% endblock %}

main/templates/main/test_detail.html
{% extends 'main/base.html' %}
{% block title %}
  {{ slug }}
{% endblock %}
{% block content %}
  <form action="/tests/{{slug}}/leave_test" method="POST">
    {% csrf_token %}
  	{% for test in tests %}
    
      <div class="form-box">
          <h3 class="form-text-h">{{ test.question }}</h1>
            {% if test.img %}
              <img src="{{test.img.url}}"><br>
            {% endif %}
          
          <input class="form-input" id="{{ test.question }}{{ test.answer1 }}" type="radio" name="{{ test.question }}" value="{{ test.answer1 }}" required><label for="{{ test.question }}{{ test.answer1 }}">A) {{ test.answer1 }}</label><br>
          <input class="form-input" id="{{ test.question }}{{ test.answer2 }}" type="radio" name="{{ test.question }}" value="{{ test.answer2 }}"><label for="{{ test.question }}{{ test.answer2 }}">B) {{ test.answer2 }}</label><br>
          <input class="form-input" id="{{ test.question }}{{ test.answer3 }}" type="radio" name="{{ test.question }}" value="{{ test.answer3 }}"><label for="{{ test.question }}{{ test.answer3 }}">C) {{ test.answer3 }}</label><br>
          <input class="form-input" id="{{ test.question }}{{ test.answer4 }}" type="radio" name="{{ test.question }}" value="{{ test.answer4 }}"><label for="{{ test.question }}{{ test.answer4 }}">D) {{ test.answer4 }}</label><br>
          <input class="form-input" id="{{ test.question }}{{ test.answer5 }}" type="radio" name="{{ test.question }}" value="{{ test.answer5 }}"><label for="{{ test.question }}{{ test.answer5 }}">E) {{ test.answer5 }}</label><br>
      </div>
    {% endfor %}
    <div class="form">
      <button class="btn" type="submit">Отправить</button>
    </div>
  </form>
{% endblock %}

main/templates/main/test_details.html
{% extends 'main/base.html' %}
{% block title %}
  {{ slug }}
{% endblock %}
{% block content %}
  <form action="/tests/{{slug}}/leave_test" method="POST">
    {% csrf_token %}
    <div class="content-bigbox-gray">
    	{% for test in tests %}
        <div class="content-bigbox-test">
            <h1 class="content-bigbox-text-h">{{ test.question }}</h1>
            <input class="input" id="1" type="radio" name="{{ test.question }}" value="A)" required><label for="1">A) {{ test.answer1 }}</label><br>
            <input class="input" id="2" type="radio" name="{{ test.question }}" value="B)"><label for="2">B) {{ test.answer2 }}</label><br>
            <input class="input" id="3" type="radio" name="{{ test.question }}" value="C)"><label for="3">C) {{ test.answer3 }}</label><br>
            <input class="input" id="4" type="radio" name="{{ test.question }}" value="D)"><label for="4">D) {{ test.answer4 }}</label><br>
            <input class="input" id="5" type="radio" name="{{ test.question }}" value="D)"><label for="5">E) {{ test.answer5 }}</label><br>
        </div>
      {% endfor %}
      <div class="content-bigbox-test-v">
        <button class="asd" type="submit">Отправить</button>
      </div>
    </div>
  </form>
{% endblock %}

main/templates/main/tests.html
{% extends 'main/base.html' %}
{% block title %}
{{ title }}
{% endblock %}

{% block content %}
  <div class="content-boxes">
{% for el in article %}
  
    <div class="content-box">
      <a href="{{el.get_test_url }}" class='content-box-link'>
      <img class="content-box-img" src="{{ el.article_img1.url }}" alt="Картинка">
      <p class="content-h2">Тест {{ el.article_title }}</p>
      </a>
    </div>
    
    
{% endfor %}
  </div>
{% endblock %}